spring:
  flyway:
    url: jdbc:postgresql://habitquest-postgres/habitquestdb_marketplace
  r2dbc:
    url: r2dbc:postgresql://habitquest-postgres/habitquestdb_marketplace
  # rabbitmq:
  #   host: marketplace-rabbitmq
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://habitquest-keycloak/realms/HabitQuest
# app:
#   rabbit:
#     exchange: payment.exchange
#     exchange-type: fanout
