apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-service
  labels:
    app: marketplace-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-service
  template:
    metadata:
      labels:
        app: marketplace-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9003"
    spec:
      containers:
        - name: marketplace-service
          image: marketplace-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9003
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9003
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9003
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: marketplace-config-volume
              mountPath: /workspace/config
      volumes:
        - name: marketplace-config-volume
          configMap:
            name: marketplace-config
