name: Release
on:
  workflow_run:
    workflows: ['Build and Package']
    types: [completed]
concurrency: release

env:
  OWNER: myhabitquest
  REGISTRY: ghcr.io
  APP_REPO: marketplace-service
  DEPLOY_REPO: habitquest-deployment
  VERSION: ${{ github.sha }}

jobs:
  deliver:
    name: Deliver release candidate to production
    runs-on: ubuntu-22.04
    steps:
      - name: Deliver application to production
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ env.OWNER }}/${{ env.DEPLOY_REPO }}
          event-type: app_delivery
          client-payload: '{
            "app_image": "${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.APP_REPO }}",
            "app_name": "${{ env.APP_REPO }}",
            "app_version": "${{ env.VERSION }}"
          }'
